modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/BOLTMAGIC/EnchantLimiter/issues"
[[mods]]
modId="enchantlimiter"
version="${file.jarVersion}"
displayName="Enchantment Limiter"

logoFile="examplemod.png"
credits="Content Council"
authors="Jackiecrazy, BOLTM4G1C"
description='''
Limits the amount of enchantments that can go on a single item, based on its enchantability.
'''
[[dependencies.enchantlimiter]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enchantlimiter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enchantlimiter]]
    modId="ftbteams"
    mandatory=false
    versionRange="[2001.3,)"
    ordering="AFTER"
    side="SERVER"
